### ISSUE TITLE
Compare it to other implementations

### ISSUE THREAD

**Issue by tailhook** [oldaniel/zap#5]
Hi,

It would be nice if you could explain just in few sentences what implementation strategy you've chosen that makes your implementation faster.

I'm the co-author of [tk-http](https://github.com/swindon-rs/tk-http) yet another http implementation in rust. It's also different from hyper in several things, in particular of how buffering is done and makes API more low-level allowing more optimizations on application level (i.e. de/serialize right into connection buffer, etc.). Also, we don't try to parse headers into type-safe things proactively (i.e. only parse headers need for this specific handler) which also saves CPU and avoids many memory allocations.

I haven't tested performance lately, as we focus more on correctness, but we are already running our implementation in production and it works pretty nice (as part of [swindon](https://github.com/swindon-rs/swindon) project).

By writing this I'm trying to say that if your implementation makes similar assumptions and optimizations it would be great to join our effort.

**Comment by ghost** [comment]
@tailhook Sorry for my late response, I was a bit busy with school. I will explain it in the wiki on a better way and work on more optimizations.

I will check out your work as well and maybe I find a way to contribute as well.

**Comment by ghost** [comment]
@tailhook I think cause of the new goal of this project this issue can be closed.

**The new goal:** Showing how fast rust can be, just a test project.

_(@daniel-Q6wUOI is my old account)_
